name: Build & lint project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress -vvv
      - name: Check coding standards for modules and theme
        uses: docker://hussainweb/drupalqa:php8.2
        with:
          args: phpcs --standard="Drupal,DrupalPractice" -n --extensions="php,module,install,theme" drupal-data/web/modules/custom/my_module --ignore=web/themes/*/dist/,web/themes/*/Gulpfile.js,web/themes/*/node_modules/